spring.application.name=hamyeon

# initializr?? H2 ???? ???? ??????? ?? ??? ??????,
# ???? ?? ???? ???? ???? ??? ???? ?? ??

# ???? db(H2) ?? ??

# 1. Datasource ?? (H2 ???? ??????)
# ?? URL ??
spring.datasource.url=jdbc:h2:mem:testdb 
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 2. H2 ? ?? ??:??? ?? ? ?? ?????? db ?? ?? ??? ?? ?? ???
# ????? ?? db ??? ?? ? ?? ??? ????? ????. ??? ????? ??? ????
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# 3. JPA ? Hibernate ??
#???? ??? ?? ????? JPA? SQL ???? ??? ?? ??.spring.jpa.show-sql=true? ?? ???
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#??? entity ???? ????, ?? ?? ? ???? db ??? ?? ?? ??(update:?? ??? ??)->?? ??? ?? ?? ?????, h2 ???:create-drop. ?? ? ??? ??, ??? ?? ??? ???
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
